FROM bitnami/spark:latest

# MongoDB Spark Connector
COPY mongo-spark-connector_2.12-10.0.0.jar /opt/bitnami/spark/jars/

COPY spark_app.py /opt/bitnami/spark/app/

WORKDIR /opt/bitnami/spark/app

CMD ["/opt/bitnami/spark/bin/spark-submit", "--master", "local", "spark_app.py"]
